language: generic
env:
  - REPO=web-platform-tests
    TO_USER=jeremypoulter
    TO_BRANCH=w3c_tracking
    FROM="w3c master $TO_USER master"
  - REPO=web-platform-tests
    TO_USER=jeremypoulter
    TO_BRANCH=w3c_mirror
    FROM="w3c master $TO_USER master"
  - REPO=wpt-tools
    TO_USER=jeremypoulter
    TO_BRANCH=w3c_tracking
    FROM="w3c master $TO_USER master"
  - REPO=wpt-tools
    TO_USER=jeremypoulter
    TO_BRANCH=w3c_mirror
    FROM="w3c master $TO_USER master"
before_install:
  - openssl aes-256-cbc -K $encrypted_686b3bfbef0f_key -iv $encrypted_686b3bfbef0f_iv -in keys.tar.enc -out keys.tar -d
  - tar xvf keys.tar
  - sudo apt-get -qq update
  - sudo apt-get install -y realpath
script:
  - ssh-agent bash -c "ssh-add keys/$REPO.pem; bash fork_sync.sh $REPO $TO_USER $TO_BRANCH $FROM"
